#开发环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:49999/test?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Summit2017
  redis:
    host: localhost
    port: 10001
eureka:
  instance:
    #使用IP注册服务
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: "http://ucp:Summit2018@localhost:45000/eureka/"

### 通用文件
summit:
  file:
    # 项目文件 直接放入到 resources/file 下，并指定名称，多个用逗号隔开
    project:
      file-name: test.docx